INSERT INTO REFDATA_INDUSTRYSTD (INDUSTRY_STD, INDUSTRYSTD_DESCRIPTION, STATUS_ID, CREATED_DATE) VALUES ('HL7', null, 'ACTIVE', '2024-12-14 01:19:48');
INSERT INTO REFDATA_INDUSTRYSTD (INDUSTRY_STD, INDUSTRYSTD_DESCRIPTION, STATUS_ID, CREATED_DATE) VALUES ('X12', null, 'ACTIVE', '2024-12-14 01:19:48');
INSERT INTO REFDATA_INDUSTRYSTD (INDUSTRY_STD, INDUSTRYSTD_DESCRIPTION, STATUS_ID, CREATED_DATE) VALUES ('HIPPA', null, 'ACTIVE', '2024-12-14 01:19:48');
INSERT INTO REFDATA_INDUSTRYSTD (INDUSTRY_STD, INDUSTRYSTD_DESCRIPTION, STATUS_ID, CREATED_DATE) VALUES ('NCPDP', null, 'ACTIVE', '2024-12-14 01:19:48');
